"""Add Canva token to user model

Revision ID: 1d429cb22e19
Revises: 0cb768c06e97
Create Date: 2025-12-24 17:43:22.669586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d429cb22e19'
down_revision = '0cb768c06e97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('canva_access_token', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('canva_refresh_token', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('canva_token_expiry', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'companies', ['company_id'], ['id'], ondelete='SET NULL', use_alter=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('canva_token_expiry')
        batch_op.drop_column('canva_refresh_token')
        batch_op.drop_column('canva_access_token')

    # ### end Alembic commands ###
