"""add admin roles

Revision ID: 346808b6a172
Revises: 74ef5440dbfc
Create Date: 2026-01-23 11:49:49.244763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '346808b6a172'
down_revision = '74ef5440dbfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.Enum('super_admin', 'business_admin', 'support_admin', name='admin_roles'), nullable=False))
        batch_op.add_column(sa.Column('permissions', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_column('permissions')
        batch_op.drop_column('role')

    # ### end Alembic commands ###
