"""Add session_id and sender_type to SupportWidgetMessage

Revision ID: 74ef5440dbfc
Revises: e4a86a24bb1c
Create Date: 2026-01-22 15:32:54.306824

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '74ef5440dbfc'
down_revision = 'e4a86a24bb1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('support_widget_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('sender_type', sa.Enum('user', 'admin', name='message_sender_types'), nullable=False))
        batch_op.add_column(sa.Column('admin_id', sa.Integer(), nullable=True))
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
        batch_op.create_foreign_key(None, 'admins', ['admin_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('support_widget_messages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
        batch_op.drop_column('admin_id')
        batch_op.drop_column('sender_type')
        batch_op.drop_column('session_id')

    # ### end Alembic commands ###
