"""change layout_style to String

Revision ID: ad30e72fc0e5
Revises: c33a99a986f5
Create Date: 2026-01-19 13:58:24.587563

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ad30e72fc0e5'
down_revision = 'c33a99a986f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.alter_column('layout_style',
               existing_type=mysql.ENUM('classic', 'modern', 'receipt', 'visual'),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.alter_column('layout_style',
               existing_type=sa.String(length=50),
               type_=mysql.ENUM('classic', 'modern', 'receipt', 'visual'),
               existing_nullable=False)

    # ### end Alembic commands ###
