"""Add referral system

Revision ID: af3709113a96
Revises: ad30e72fc0e5
Create Date: 2026-01-22 12:08:36.667500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af3709113a96'
down_revision = 'ad30e72fc0e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('referrals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('referrer_id', sa.Integer(), nullable=False),
    sa.Column('referred_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'completed', name='referral_statuses'), nullable=False),
    sa.Column('reward_claimed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['referred_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['referrer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('referral_code', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('referred_by', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(None, ['referral_code'])
        batch_op.create_foreign_key(None, 'users', ['referred_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('referred_by')
        batch_op.drop_column('referral_code')

    op.drop_table('referrals')
    # ### end Alembic commands ###
