"""Added is_premium to Template

Revision ID: c33a99a986f5
Revises: cf956d1fd4a8
Create Date: 2026-01-19 13:27:57.371470

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c33a99a986f5'
down_revision = 'cf956d1fd4a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_premium', sa.Boolean(), nullable=False))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('canva_token_expiry')
        batch_op.drop_column('canva_access_token')
        batch_op.drop_column('canva_code_verifier')
        batch_op.drop_column('canva_refresh_token')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('canva_refresh_token', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('canva_code_verifier', mysql.VARCHAR(length=128), nullable=True))
        batch_op.add_column(sa.Column('canva_access_token', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('canva_token_expiry', mysql.DATETIME(), nullable=True))

    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.drop_column('is_premium')

    # ### end Alembic commands ###
