"""Add canva_code_verifier for PKCE

Revision ID: cf956d1fd4a8
Revises: 1d429cb22e19
Create Date: 2025-12-25 17:54:31.364591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf956d1fd4a8'
down_revision = '1d429cb22e19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('canva_code_verifier', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('canva_code_verifier')

    # ### end Alembic commands ###
